version: '3.1'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: accounts
      MYSQL_USER: example
      MYSQL_PASSWORD: secret123
      MYSQL_ROOT_PASSWORD: secret123
    ports:
      - "3306:3306"
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=sns
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
#      arn:aws:sns:us-east-1:000000000000:AccountsEvents